"""Turn a :class:`QueryResponse` into something another tool can open.

Two audiences, two formats:

* **CSV** for spreadsheets. One row per patient, flat, with the analytics columns only
  when the question asked for analytics. Spreadsheet applications execute cells that
  look like formulas, and patient ids, genders and concept names all originate on a
  FHIR server this service does not control, so every text cell is neutralised before
  it is written (OWASP "CSV injection").
* **FHIR** for other FHIR systems. The cohort becomes an R4 ``Group`` of actual
  ``Patient`` references, optionally wrapped in a ``collection`` ``Bundle``. The FHIR
  queries that produced it travel with it as extensions, so a reviewer on the receiving
  side can re-run them instead of trusting the list.

Every identifier is derived with :func:`uuid.uuid5` from the question and the patient
ids. The same answer always exports byte-for-byte identically, which is what makes two
exports diffable and an export reviewable in version control.

This module is pure: no I/O, no FastAPI, no clock.
"""

from __future__ import annotations

import csv
import html
import io
import uuid
from typing import Any

from fhir_healthcare_ai.domain.results import QueryResponse

#: Base for the extension and tag systems this service defines. A URL we control rather
#: than a made-up host, so the identifiers resolve to something a reader can look up.
_BASE_URL = "https://github.com/martinoa2000/fhir-healthcare-ai/fhir"
EXECUTED_QUERY_EXTENSION = f"{_BASE_URL}/StructureDefinition/executed-query"
DISCLAIMER_EXTENSION = f"{_BASE_URL}/StructureDefinition/disclaimer"
TAG_SYSTEM = f"{_BASE_URL}/CodeSystem/export-tag"

#: Namespace for every uuid5 in an export. Fixed forever: changing it would change every
#: previously exported id.
_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, f"{_BASE_URL}/export")

FHIR_MEDIA_TYPE = "application/fhir+json"
CSV_MEDIA_TYPE = "text/csv"

BASE_COLUMNS: tuple[str, ...] = (
    "patient_id",
    "age_years",
    "gender",
    "matched_steps",
    "evidence_count",
)
ANALYSIS_COLUMNS: tuple[str, ...] = ("risk_score", "risk_band", "abnormal_lab_concepts")

#: Leading characters that make Excel, LibreOffice or Sheets treat a cell as a formula.
_FORMULA_PREFIXES = ("=", "+", "-", "@", "\t", "\r")

#: Marks every exported resource as generated, synthetic and not for clinical use.
#: ``HTEST`` ("test health data") is the standard HL7 code for exactly that; the second
#: tag says who generated it, in words a receiving system can show.
META_TAGS: tuple[dict[str, str], ...] = (
    {
        "system": "http://terminology.hl7.org/CodeSystem/v3-ActReason",
        "code": "HTEST",
        "display": "test health data",
    },
    {
        "system": TAG_SYSTEM,
        "code": "generated-not-for-clinical-use",
        "display": "Generated by fhir-healthcare-ai from synthetic data; not for clinical use",
    },
)


# -- CSV --------------------------------------------------------------------------


def to_csv(response: QueryResponse) -> str:
    """One row per matched patient, preceded by a header row.

    A refused or empty answer yields the header alone, so a consumer can always parse
    the columns. Analytics columns appear only when the response carries analyses;
    adding empty columns to a pure cohort search would suggest a risk score was
    computed and came back blank.
    """
    with_analysis = bool(response.analyses)
    columns = BASE_COLUMNS + (ANALYSIS_COLUMNS if with_analysis else ())
    analyses = {a.patient_id: a for a in response.analyses}

    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\r\n")
    writer.writerow(columns)
    for patient in response.patients:
        row: list[str | int | float] = [
            _safe(patient.patient_id),
            _number(patient.age_years),
            _safe(patient.gender),
            _safe(";".join(patient.matched_steps)),
            len(patient.evidence),
        ]
        if with_analysis:
            analysis = analyses.get(patient.patient_id)
            risk = analysis.risk if analysis else None
            concepts = sorted({f.concept for f in analysis.abnormal_labs}) if analysis else []
            row += [
                _number(risk.score if risk else None),
                _safe(risk.band.value if risk else None),
                _safe(";".join(concepts)),
            ]
        writer.writerow(row)
    return buffer.getvalue()


def _safe(value: str | None) -> str:
    """Neutralise a text cell so no spreadsheet evaluates it.

    The single-quote prefix is the convention spreadsheet applications themselves use
    for "this is text"; it is visible but harmless, whereas stripping the character
    would silently change the data.
    """
    if value is None:
        return ""
    return f"'{value}" if value.startswith(_FORMULA_PREFIXES) else value


def _number(value: float | None) -> str | float:
    """Numbers this module computes itself cannot carry a payload; they pass unescaped."""
    return "" if value is None else round(value, 4)


# -- FHIR -------------------------------------------------------------------------


def to_fhir_group(response: QueryResponse) -> dict[str, Any]:
    """The matched cohort as an R4 ``Group`` of actual patients.

    Deliberately carries no ``characteristic``: the membership criteria are the executed
    queries (as extensions), which are exact, rather than a lossy re-encoding of them as
    Group characteristics.
    """
    patient_ids = [p.patient_id for p in response.patients]
    question = response.question
    extensions: list[dict[str, Any]] = [
        {"url": EXECUTED_QUERY_EXTENSION, "valueString": query} for query in response.fhir_queries
    ]
    extensions.append({"url": DISCLAIMER_EXTENSION, "valueString": response.disclaimer})
    summary = f"{len(patient_ids)} patient(s) matching: {question}"
    if response.trace and response.trace.truncated:
        # quantity counts members listed; say so when the display cap cut the cohort.
        summary += " (truncated by the response cap; the full cohort is larger)"
    return {
        "resourceType": "Group",
        "id": _uuid("group", question, patient_ids),
        "meta": {"tag": [dict(tag) for tag in META_TAGS]},
        "text": {
            "status": "generated",
            "div": (
                '<div xmlns="http://www.w3.org/1999/xhtml">'
                f"<p>{html.escape(summary)}</p>"
                f"<p>{html.escape(response.disclaimer)}</p>"
                "</div>"
            ),
        },
        "extension": extensions,
        "type": "person",
        "actual": True,
        "name": f"Cohort: {question}",
        "quantity": len(patient_ids),
        "member": [{"entity": {"reference": f"Patient/{pid}"}} for pid in patient_ids],
    }


def to_fhir_bundle(response: QueryResponse) -> dict[str, Any]:
    """A ``collection`` Bundle holding the cohort ``Group``.

    Only the Group is included, not the patients' own resources: the Bundle is a
    pointer to data on the source server, not a copy of it, which keeps an export from
    becoming an unaudited bulk extract.
    """
    group = to_fhir_group(response)
    patient_ids = [p.patient_id for p in response.patients]
    return {
        "resourceType": "Bundle",
        "id": _uuid("bundle", response.question, patient_ids),
        "meta": {"tag": [dict(tag) for tag in META_TAGS]},
        "type": "collection",
        "entry": [{"fullUrl": f"urn:uuid:{group['id']}", "resource": group}],
    }


def _uuid(kind: str, question: str, patient_ids: list[str]) -> str:
    """A stable id: same question and same cohort, same id; any difference, a new one."""
    return str(uuid.uuid5(_NAMESPACE, "\n".join([kind, question, *patient_ids])))
