"""A deterministic provider that needs no API key and no network.

This is what makes ``docker compose up`` work out of the box, what makes CI meaningful,
and what makes the benchmark reproducible. It is a rule-based planner wearing the
:class:`LLMProvider` interface: it recognises the clinical intents the demo dataset
supports and emits the same JSON plan a well-behaved model would.

It is not a language model and does not pretend to be one. Questions it does not
recognise come back with ``unsupported: true`` and an honest reason, which is exactly
the behaviour the real providers are instructed to fall back to -- so the unsupported
path is exercised by default rather than only in production.

Because it is deterministic it also serves as the control arm of the benchmark: any
metric difference between ``mock`` and a real provider is attributable to the model,
not to the surrounding pipeline.
"""

from __future__ import annotations

import json
import re
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Any

from fhir_healthcare_ai.llm.base import LLMMessage, LLMProvider, LLMResponse
from fhir_healthcare_ai.logging_config import get_logger
from fhir_healthcare_ai.terminology import LOINC, RXNORM, SNOMED

logger = get_logger(__name__)

MODEL_NAME = "mock-rule-planner"

# Concept groups the rules compose plans from.
DIABETES_DRUGS: tuple[str, ...] = (
    "metformin",
    "glipizide",
    "sitagliptin",
    "empagliflozin",
    "dapagliflozin",
    "semaglutide",
    "liraglutide",
    "insulin_glargine",
)
ANTIHYPERTENSIVES: tuple[str, ...] = (
    "lisinopril",
    "losartan",
    "amlodipine",
    "hydrochlorothiazide",
    "metoprolol",
)
STATINS: tuple[str, ...] = ("atorvastatin", "simvastatin")


@dataclass(frozen=True)
class Rule:
    """One recognised question shape.

    Args:
        name: Identifier, surfaced in logs so a benchmark failure can be traced to the
            rule that fired.
        keywords: Every group must have at least one member present in the question.
            Nested tuples are OR, the outer tuple is AND.
        build: Produces the plan dict for a question that matched.
    """

    name: str
    keywords: tuple[tuple[str, ...], ...]
    build: Callable[[str, datetime], dict[str, Any]]

    def matches(self, question: str) -> bool:
        return all(any(word in question for word in group) for group in self.keywords)


class MockLLMProvider(LLMProvider):
    """Rule-based stand-in for a real model."""

    name = "mock"

    def __init__(self, *, today: datetime | None = None) -> None:
        self._today = today

    async def complete(
        self,
        messages: list[LLMMessage],
        *,
        temperature: float | None = None,
        max_tokens: int | None = None,
        json_mode: bool = False,
    ) -> LLMResponse:
        del temperature, max_tokens, json_mode
        user_text = "\n".join(m.content for m in messages if m.role == "user")

        if _is_narrative_request(messages):
            payload: Any = _narrative(user_text)
            text = str(payload)
        else:
            question = _extract_question(user_text)
            today = self._today or _extract_today(user_text) or datetime.now(UTC)
            plan = plan_for(question, today)
            logger.debug("mock planner produced a plan", extra={"question": question})
            text = json.dumps(plan, indent=2)

        return LLMResponse(
            text=text,
            model=MODEL_NAME,
            prompt_tokens=sum(len(m.content) // 4 for m in messages),
            completion_tokens=len(text) // 4,
            finish_reason="stop",
        )


def plan_for(question: str, today: datetime) -> dict[str, Any]:
    """The planner itself, exposed directly so tests need no provider plumbing."""
    lowered = question.lower()
    for rule in RULES:
        if rule.matches(lowered):
            plan = rule.build(question, today)
            plan.setdefault("assumptions", [])
            plan["assumptions"].append(f"Plan generated by the {rule.name} rule ({MODEL_NAME}).")
            return plan
    return _unsupported(question)


# -- plan builders --------------------------------------------------------------------


def _date(today: datetime, days_ago: int) -> str:
    return (today - timedelta(days=days_ago)).date().isoformat()


def _token(name: str, values: Sequence[str], system: str) -> dict[str, Any]:
    return {"name": name, "values": list(values), "system": system}


def _elevated_hba1c_with_med_change(question: str, today: datetime) -> dict[str, Any]:
    return {
        "question": question,
        "intent": "cohort_search",
        "rationale": (
            "Select patients by an out-of-target HbA1c, then restrict to those whose "
            "glucose-lowering therapy changed recently."
        ),
        "cohort_logic": "all",
        "steps": [
            {
                "step_id": "elevated_hba1c",
                "resource_type": "Observation",
                "purpose": "HbA1c results above the 7% general target within the last year.",
                "params": [
                    _token("code", ["hba1c"], LOINC),
                    {"name": "value-quantity", "values": ["7"], "comparator": "gt", "unit": "%"},
                    {"name": "date", "values": [_date(today, 365)], "comparator": "ge"},
                ],
                "sort": "-date",
                "count": 200,
            },
            {
                "step_id": "recent_med_change",
                "resource_type": "MedicationRequest",
                "purpose": "Glucose-lowering orders authored in the last 90 days.",
                "depends_on": "elevated_hba1c",
                "params": [
                    _token("code", DIABETES_DRUGS, RXNORM),
                    {"name": "authoredon", "values": [_date(today, 90)], "comparator": "ge"},
                ],
                "count": 200,
            },
        ],
        "analysis": {"type": "abnormal_labs", "concepts": ["hba1c"], "lookback_days": 365},
        "assumptions": [
            "'elevated HbA1c' was read as a result above 7%.",
            "'recent' was read as the last 90 days.",
            "'diabetes medication' covers the glucose-lowering classes in the concept list.",
        ],
        "unsupported": False,
        "unsupported_reason": None,
    }


def _elevated_hba1c(question: str, today: datetime) -> dict[str, Any]:
    return {
        "question": question,
        "intent": "cohort_search",
        "rationale": "Select patients by an HbA1c result above the 7% general target.",
        "cohort_logic": "all",
        "steps": [
            {
                "step_id": "elevated_hba1c",
                "resource_type": "Observation",
                "purpose": "HbA1c results above 7% within the last year.",
                "params": [
                    _token("code", ["hba1c"], LOINC),
                    {"name": "value-quantity", "values": ["7"], "comparator": "gt", "unit": "%"},
                    {"name": "date", "values": [_date(today, 365)], "comparator": "ge"},
                ],
                "sort": "-date",
                "count": 200,
            }
        ],
        "analysis": {"type": "abnormal_labs", "concepts": ["hba1c"], "lookback_days": 365},
        "assumptions": ["'elevated' was read as an HbA1c above 7%."],
        "unsupported": False,
        "unsupported_reason": None,
    }


def _ckd_cohort(question: str, today: datetime) -> dict[str, Any]:
    return {
        "question": question,
        "intent": "cohort_search",
        "rationale": "Select patients with a reduced eGFR, then confirm a recorded CKD diagnosis.",
        "cohort_logic": "all",
        "steps": [
            {
                "step_id": "low_egfr",
                "resource_type": "Observation",
                "purpose": "eGFR below 60 mL/min/1.73m2 within the last year.",
                "params": [
                    _token("code", ["egfr"], LOINC),
                    {
                        "name": "value-quantity",
                        "values": ["60"],
                        "comparator": "lt",
                        "unit": "mL/min/1.73m2",
                    },
                    {"name": "date", "values": [_date(today, 365)], "comparator": "ge"},
                ],
                "sort": "-date",
                "count": 200,
            },
            {
                "step_id": "ckd_diagnosis",
                "role": "context",
                "resource_type": "Condition",
                "purpose": "An active chronic kidney disease problem for those patients.",
                "depends_on": "low_egfr",
                "params": [
                    _token("code", ["chronic_kidney_disease"], SNOMED),
                    {"name": "clinical-status", "values": ["active"]},
                ],
                "count": 200,
            },
        ],
        "analysis": {
            "type": "risk_stratification",
            "concepts": ["egfr", "creatinine", "urine_albumin_creatinine_ratio"],
            "lookback_days": 365,
        },
        "assumptions": [
            "'reduced kidney function' was read as eGFR below 60 mL/min/1.73m2.",
        ],
        "unsupported": False,
        "unsupported_reason": None,
    }


def _uncontrolled_hypertension(question: str, today: datetime) -> dict[str, Any]:
    return {
        "question": question,
        "intent": "cohort_search",
        "rationale": (
            "Select patients with a raised systolic blood pressure, then confirm they are "
            "already on an antihypertensive."
        ),
        "cohort_logic": "all",
        "steps": [
            {
                "step_id": "high_systolic",
                "resource_type": "Observation",
                "purpose": "Systolic blood pressure at or above 140 mmHg in the last year.",
                "params": [
                    _token("code", ["systolic_bp", "blood_pressure_panel"], LOINC),
                    {
                        "name": "component-value-quantity",
                        "values": ["140"],
                        "comparator": "ge",
                        "unit": "mm[Hg]",
                    },
                    {"name": "date", "values": [_date(today, 365)], "comparator": "ge"},
                ],
                "sort": "-date",
                "count": 200,
            },
            {
                "step_id": "on_antihypertensive",
                "resource_type": "MedicationRequest",
                "purpose": "Active antihypertensive therapy for those patients.",
                "depends_on": "high_systolic",
                "params": [
                    _token("code", ANTIHYPERTENSIVES, RXNORM),
                    {"name": "status", "values": ["active"]},
                ],
                "count": 200,
            },
        ],
        "analysis": {
            "type": "risk_stratification",
            "concepts": ["systolic_bp", "diastolic_bp"],
            "lookback_days": 365,
        },
        "assumptions": ["'uncontrolled' was read as a systolic pressure of 140 mmHg or above."],
        "unsupported": False,
        "unsupported_reason": None,
    }


def _diabetes_no_statin(question: str, today: datetime) -> dict[str, Any]:
    del today
    return {
        "question": question,
        "intent": "cohort_search",
        "rationale": (
            "Retrieve the diabetic cohort and their lipid-lowering orders; the absence of a "
            "statin is determined by the analytics layer, since FHIR search cannot express "
            "'has no resource of this kind'."
        ),
        "cohort_logic": "all",
        "steps": [
            {
                "step_id": "diabetes",
                "resource_type": "Condition",
                "purpose": "Patients with an active type 2 diabetes problem.",
                "params": [
                    _token("code", ["type_2_diabetes"], SNOMED),
                    {"name": "clinical-status", "values": ["active"]},
                ],
                "count": 200,
            },
            {
                "step_id": "statin_orders",
                "role": "exclude",
                "resource_type": "MedicationRequest",
                "purpose": "Statin orders for that cohort, used to exclude patients who have one.",
                "depends_on": "diabetes",
                "params": [_token("code", STATINS, RXNORM)],
                "count": 200,
            },
        ],
        "analysis": {
            "type": "cohort_identification",
            "concepts": ["ldl_cholesterol"],
            "lookback_days": 365,
        },
        "assumptions": [
            "Negation is resolved after retrieval: FHIR search has no 'absent resource' filter.",
        ],
        "unsupported": False,
        "unsupported_reason": None,
    }


def _patient_summary(question: str, today: datetime) -> dict[str, Any]:
    patient_id = _extract_patient_id(question) or "unknown"
    return {
        "question": question,
        "intent": "patient_summary",
        "rationale": "Retrieve one patient's recent clinical record for summarisation.",
        "cohort_logic": "all",
        "steps": [
            {
                "step_id": "patient",
                "resource_type": "Patient",
                "purpose": "The patient's demographics.",
                "params": [{"name": "_id", "values": [patient_id]}],
                "count": 1,
            },
            {
                "step_id": "observations",
                "role": "context",
                "resource_type": "Observation",
                "purpose": "Recent laboratory and vital sign results.",
                "params": [
                    {"name": "patient", "values": [patient_id]},
                    {"name": "date", "values": [_date(today, 365)], "comparator": "ge"},
                ],
                "sort": "-date",
                "count": 200,
            },
            {
                "step_id": "conditions",
                "role": "context",
                "resource_type": "Condition",
                "purpose": "The active problem list.",
                "params": [
                    {"name": "patient", "values": [patient_id]},
                    {"name": "clinical-status", "values": ["active"]},
                ],
                "count": 100,
            },
            {
                "step_id": "medications",
                "role": "context",
                "resource_type": "MedicationRequest",
                "purpose": "Current medication orders.",
                "params": [{"name": "patient", "values": [patient_id]}],
                "count": 100,
            },
        ],
        "analysis": {"type": "abnormal_labs", "concepts": [], "lookback_days": 365},
        "assumptions": ["The summary window was taken as the last 12 months."],
        "unsupported": False,
        "unsupported_reason": None,
    }


def _high_risk_cohort(question: str, today: datetime) -> dict[str, Any]:
    return {
        "question": question,
        "intent": "cohort_search",
        "rationale": (
            "Retrieve the diabetic cohort with their recent results so the risk model can "
            "stratify them."
        ),
        "cohort_logic": "all",
        "steps": [
            {
                "step_id": "diabetes",
                "resource_type": "Condition",
                "purpose": "Patients with an active diabetes problem.",
                "params": [
                    _token("code", ["type_2_diabetes", "type_1_diabetes"], SNOMED),
                    {"name": "clinical-status", "values": ["active"]},
                ],
                "count": 200,
            },
            {
                "step_id": "recent_results",
                "role": "context",
                "resource_type": "Observation",
                "purpose": "Results the risk model consumes.",
                "depends_on": "diabetes",
                "params": [
                    _token(
                        "code",
                        [
                            "hba1c",
                            "egfr",
                            "creatinine",
                            "systolic_bp",
                            "urine_albumin_creatinine_ratio",
                        ],
                        LOINC,
                    ),
                    {"name": "date", "values": [_date(today, 365)], "comparator": "ge"},
                ],
                "sort": "-date",
                "count": 200,
            },
        ],
        "analysis": {
            "type": "risk_stratification",
            "concepts": ["hba1c", "egfr", "systolic_bp"],
            "lookback_days": 365,
        },
        "assumptions": [
            "Risk is computed by the demonstration model and is not a clinical judgement.",
        ],
        "unsupported": False,
        "unsupported_reason": None,
    }


def _abnormal_potassium(question: str, today: datetime) -> dict[str, Any]:
    return {
        "question": question,
        "intent": "cohort_search",
        "rationale": "Select patients with a potassium result outside the reference interval.",
        "cohort_logic": "any",
        "steps": [
            {
                "step_id": "potassium_results",
                "resource_type": "Observation",
                "purpose": "Potassium results in the last 6 months.",
                "params": [
                    _token("code", ["potassium"], LOINC),
                    {"name": "date", "values": [_date(today, 180)], "comparator": "ge"},
                ],
                "sort": "-date",
                "count": 200,
            }
        ],
        "analysis": {
            "type": "abnormal_labs",
            "concepts": ["potassium"],
            "lookback_days": 180,
            "options": {"require_abnormal": True},
        },
        "assumptions": [
            "Abnormality is decided by the analytics layer against the reference interval, "
            "not by a value filter in the query.",
        ],
        "unsupported": False,
        "unsupported_reason": None,
    }


def _unsupported(question: str) -> dict[str, Any]:
    return {
        "question": question,
        "intent": "cohort_search",
        "rationale": "No rule in the deterministic planner matched this question.",
        "cohort_logic": "all",
        "steps": [],
        "analysis": {"type": "none", "concepts": [], "lookback_days": None},
        "assumptions": [],
        "unsupported": True,
        "unsupported_reason": (
            f"The {MODEL_NAME} provider recognises a fixed set of question shapes and this "
            "is not one of them. Start the local model (docker compose --profile vllm up, or "
            "LLM_PROVIDER=huggingface) for open-ended questions."
        ),
    }


# Order matters: the most specific rule must be tried first.
RULES: tuple[Rule, ...] = (
    Rule(
        "hba1c_with_medication_change",
        (
            ("hba1c", "a1c", "glycated", "glycosylated"),
            ("medication", "therapy", "treatment", "drug"),
            ("change", "changed", "new", "started", "switch", "adjust", "recent"),
        ),
        _elevated_hba1c_with_med_change,
    ),
    Rule(
        "diabetes_without_statin",
        (("diabet",), ("statin", "lipid", "cholesterol"), ("without", "not on", "no ", "lack")),
        _diabetes_no_statin,
    ),
    Rule(
        "high_risk_diabetes",
        (("diabet",), ("risk", "deteriorat", "stratif", "prioriti")),
        _high_risk_cohort,
    ),
    Rule(
        "uncontrolled_hypertension",
        (
            ("blood pressure", "hypertens", "systolic", "bp "),
            ("uncontrolled", "high", "elevated", "raised", "above"),
        ),
        _uncontrolled_hypertension,
    ),
    Rule(
        "reduced_kidney_function",
        (("kidney", "renal", "egfr", "ckd", "nephropathy"),),
        _ckd_cohort,
    ),
    Rule(
        "abnormal_potassium",
        (("potassium", "kalemia", "electrolyte"),),
        _abnormal_potassium,
    ),
    Rule(
        "patient_summary",
        (("summar", "overview", "profile", "record of"), ("patient",)),
        _patient_summary,
    ),
    Rule(
        "elevated_hba1c",
        (("hba1c", "a1c", "glycated"),),
        _elevated_hba1c,
    ),
)


# -- prompt parsing -------------------------------------------------------------------

_QUESTION = re.compile(r"^Question:\s*(.+?)\s*$", re.MULTILINE)
_TODAY = re.compile(r"Today's date is (\d{4}-\d{2}-\d{2})")
_PATIENT_ID = re.compile(r"\b(?:patient(?:\s+id)?[:\s]+)([A-Za-z0-9\-.]{1,64})", re.IGNORECASE)


def _extract_question(text: str) -> str:
    match = _QUESTION.search(text)
    return match.group(1).strip() if match else text.strip()


def _extract_today(text: str) -> datetime | None:
    match = _TODAY.search(text)
    if not match:
        return None
    return datetime.fromisoformat(match.group(1)).replace(tzinfo=UTC)


def _extract_patient_id(question: str) -> str | None:
    match = _PATIENT_ID.search(question)
    return match.group(1) if match else None


def _is_narrative_request(messages: Sequence[LLMMessage]) -> bool:
    return any("You summarise the results" in m.content for m in messages if m.role == "system")


def _narrative(user_text: str) -> str:
    """A factual restatement. It adds no number that was not handed to it."""
    question = _extract_question(user_text)
    count_match = re.search(r"Patients matched:\s*(\d+)", user_text)
    count = count_match.group(1) if count_match else "an unreported number of"
    return (
        f"The query for {question.rstrip('?').lower()} matched {count} patients in the "
        "synthetic dataset. Supporting resources are listed as evidence alongside each "
        "patient. These results are retrieval output for review, not a clinical assessment."
    )
